[config]
# models
model="meta-llama/Llama-2-7b-chat-hf"
model_turbo="gpt-3.5-turbo-1106"
fallback_models=["gpt-4o-2024-05-13", "gpt-4-32k", "gpt-3.5-turbo", "anthropic/claude-3-5-sonnet-20240620", "claude-2"]